server:
  port: 8088

database-config:
  port: 3306
  username: test-master
  password: 12345678910
  url: jdbc:mysql://localhost:3306/test

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coursenet
    username: jasson.harsojo
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: update

salt:
  hash:
    password: Coursenet2023

jwt:
  token:
    issuer: course-net-application-2023
    accessExpiration: 86400 # 24 hours
    refreshExpiration: 864000 # 10 days
    secret: course-net-application-demo-secret